openapi: 3.0.0
info:
  description: Describes the API of Listings service
  title: Listings API
  version: 1.0.0
servers:
- url: /
security:
- BearerAuth: []
paths:
  /api/private/users/currrent/listings/{listingId}:
    get:
      operationId: getListingPrivateDetails
      parameters:
      - description: Listing ID
        in: path
        name: listingId
        required: true
        schema:
          $ref: '#/components/schemas/ListingIdDTO'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetListingPrivateDetailsResponse'
          description: Private details of listing
        "401":
          description: Not valid Token
        "404":
          description: Not found
      summary: Get private details for listing
      tags:
      - queriesPrivate
      x-accepts: application/json
      x-tags:
      - tag: queriesPrivate
  /api/private/users/currrent/listings:
    get:
      operationId: getOwnListings
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ListingPrivateDetailsDTO'
                type: array
          description: Private details of listing
        "403":
          description: Forbidden
      summary: List own listings
      tags:
      - queriesPrivate
      x-accepts: application/json
      x-tags:
      - tag: queriesPrivate
  /api/private/listings:
    post:
      operationId: addListing
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddListingRequestBody'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddListingResponse'
          description: Listing added successfully
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addListing_401_response'
          description: Not valid Token
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Not found
      summary: Add a new listing
      tags:
      - commandsModifications
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: commandsModifications
  /api/private/listings/{listingId}/photos/get-upload-url:
    post:
      operationId: generateUploadListingPhotoUrl
      parameters:
      - description: Listing Id
        in: path
        name: listingId
        required: true
        schema:
          $ref: '#/components/schemas/ListingIdDTO'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateUploadListingPhotoUrlRequestBody'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateUploadListingPhotoUrlResponseBody'
          description: OK
      summary: Generate upload form for listing photo
      tags:
      - commandsListingsPhoto
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: commandsListingsPhoto
  /api/private/listings/{listingId}/photos/add:
    post:
      operationId: addPhotoToListing
      parameters:
      - description: Listing Id
        in: path
        name: listingId
        required: true
        schema:
          $ref: '#/components/schemas/ListingIdDTO'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddListingPhotoRequestBody'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddListingPhotoResponseBody'
          description: Photo attached
        "403":
          description: User is not authorized
      summary: Add photo to a listing
      tags:
      - commandsListingsPhoto
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: commandsListingsPhoto
  /api/private/listings/{listingId}/photos/{photoId}:
    delete:
      operationId: deletePhoto
      parameters:
      - description: Listing Id
        in: path
        name: listingId
        required: true
        schema:
          $ref: '#/components/schemas/ListingIdDTO'
      - description: Listing Id
        in: path
        name: photoId
        required: true
        schema:
          $ref: '#/components/schemas/ListingPhotoIdDTO'
      responses:
        "204":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddListingPhotoResponseBody'
          description: Photo attached
        "403":
          description: User is not authorized
      summary: Delete photo from a listing
      tags:
      - commandsListingsPhoto
      x-accepts: application/json
      x-tags:
      - tag: commandsListingsPhoto
components:
  schemas:
    ListingIdDTO:
      format: uuid
      type: string
    GetListingPrivateDetailsResponse:
      example:
        listing:
          guestCapacity:
            infants: 0
            children: 3
            adults: 2
          address:
            country: USA
            city: San Francisco
            street: 123 Main St
          propertyType: null
          description: description
          location: "{}"
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          title: title
          roomType: null
          status: null
      properties:
        listing:
          $ref: '#/components/schemas/ListingPrivateDetailsDTO'
      required:
      - listing
      type: object
    ListingPrivateDetailsDTO:
      example:
        guestCapacity:
          infants: 0
          children: 3
          adults: 2
        address:
          country: USA
          city: San Francisco
          street: 123 Main St
        propertyType: null
        description: description
        location: "{}"
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        title: title
        roomType: null
        status: null
      properties:
        id:
          format: uuid
          type: string
        title:
          type: string
        status:
          $ref: '#/components/schemas/ListingStatusDTO'
        description:
          type: string
        guestCapacity:
          $ref: '#/components/schemas/GuestsCapacityDTO'
        propertyType:
          $ref: '#/components/schemas/PropertyTypeDTO'
        roomType:
          $ref: '#/components/schemas/RoomTypeDTO'
        address:
          $ref: '#/components/schemas/AddressDTO'
        location:
          type: object
      required:
      - id
      - status
      - title
      type: object
    AddListingRequestBody:
      example:
        operationId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        title: title
      properties:
        operationId:
          format: uuid
          type: string
        title:
          maxLength: 1000
          type: string
      required:
      - operationId
      - title
      type: object
    AddListingResponse:
      example:
        listingId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        listingId:
          format: uuid
          type: string
      required:
      - listingId
      type: object
    ValidationErrorDTO:
      properties:
        type:
          default: validationError
          type: string
        errors:
          items:
            $ref: '#/components/schemas/ValidationErrorDetailsDTO'
          type: array
      required:
      - errors
      - type
      type: object
    ValidationErrorDetailsDTO:
      properties:
        path:
          type: string
        message:
          type: string
        code:
          type: string
      required:
      - code
      - message
      - path
      type: object
    ErrorDTO:
      properties:
        code:
          type: string
        message:
          type: string
      required:
      - code
      - message
      type: object
    GenerateUploadListingPhotoUrlRequestBody:
      example:
        fileName: fileName
        fileSize: 0
        fileExtension: fileExtension
        operationId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        operationId:
          format: uuid
          type: string
        fileName:
          type: string
        fileExtension:
          maxLength: 10
          type: string
        fileSize:
          format: unsignedInt32
          type: integer
      type: object
    GenerateUploadListingPhotoUrlResponseBody:
      example:
        objectPath:
          bucketName: bucketName
          objectName: objectName
          url: url
        formData:
          key: formData
      properties:
        objectPath:
          $ref: '#/components/schemas/UploadedFileDataDTO'
        formData:
          additionalProperties:
            type: string
          type: object
      required:
      - formData
      - objectPath
      type: object
    UploadedFileDataDTO:
      example:
        bucketName: bucketName
        objectName: objectName
        url: url
      properties:
        url:
          type: string
        bucketName:
          type: string
        objectName:
          type: string
      required:
      - bucketName
      - objectName
      - url
      type: object
    AddListingPhotoRequestBody:
      example:
        operationId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        uploadedFile:
          bucketName: bucketName
          objectName: objectName
          url: url
      properties:
        operationId:
          format: uuid
          type: string
        uploadedFile:
          $ref: '#/components/schemas/UploadedFileDataDTO'
      required:
      - operationId
      - uploadedFile
      type: object
    AddListingPhotoResponseBody:
      example:
        listingPhotoId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        operationId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        operationId:
          format: uuid
          type: string
        listingPhotoId:
          format: uuid
          type: string
      required:
      - listingPhotoId
      - operationId
      type: object
    ListingPhotoIdDTO:
      format: uuid
      type: string
    ListingStatusDTO:
      enum:
      - PUBLISHED
      - DRAFT
      type: string
    GuestsCapacityDTO:
      example:
        infants: 0
        children: 3
        adults: 2
      properties:
        adults:
          maximum: 16
          minimum: 1
          type: integer
        children:
          maximum: 5
          minimum: 0
          type: integer
        infants:
          maximum: 5
          minimum: 0
          type: integer
      required:
      - adults
      - children
      - infants
      type: object
    PropertyTypeDTO:
      enum:
      - APARTMENT
      - HOUSE
      - VILLA
      - CABIN
      - COTTAGE
      - CHALET
      - BUNGALOW
      - TOWNHOUSE
      - GUESTHOUSE
      - LOFT
      - HOSTEL
      - BOAT
      - BEDANDBREAKFAST
      - OTHER
      type: string
    RoomTypeDTO:
      enum:
      - ENTIRE_PLACE
      - PRIVATE_ROOM
      - SHARED_ROOM
      type: string
    AddressDTO:
      example:
        country: USA
        city: San Francisco
        street: 123 Main St
      properties:
        street:
          example: 123 Main St
          maxLength: 255
          type: string
        city:
          example: San Francisco
          maxLength: 255
          type: string
        country:
          example: USA
          maxLength: 255
          type: string
      type: object
    LocationDTO:
      type: object
    OperationIdDTO:
      format: uuid
      type: string
    addListing_401_response:
      oneOf:
      - $ref: '#/components/schemas/ValidationErrorDTO'
      - $ref: '#/components/schemas/ErrorDTO'
      x-one-of-name: AddListing401Response
  securitySchemes:
    BearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
